### ISSUE TITLE
Replace icon library

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1049]
Replace [Material Icon](https://material.io/icons/) library with [this one](https://materialdesignicons.com/) to extend number of icons.

**Comment by ershovaelena** [comment]
Includes #990

**Comment by tamazlykar** [comment]
Test on tamazlykar/1049-icons
Test all icons

**Comment by rennervo** [comment]
Progress of task testing:

1. Google Chrome
- [ ] VM
- [ ] Storage
- [ ] Snapshots
- [ ] Images
- [ ] Firewall
- [ ] Activity log
- [ ] SSH
- [ ] Accounts
- [ ] Settings
- [ ] General

2. FireFox
- [ ] VM
- [ ] Storage
- [ ] Snapshots
- [ ] Images
- [ ] Firewall
- [ ] Activity log
- [ ] SSH
- [ ] Accounts
- [ ] Settings
- [ ] General

3. Opera
- [ ] VM
- [ ] Storage
- [ ] Snapshots
- [ ] Images
- [ ] Firewall
- [ ] Activity log
- [ ] SSH
- [ ] Accounts
- [ ] Settings
- [ ] General

4. Edge
- [ ] VM
- [ ] Storage
- [ ] Snapshots
- [ ] Images
- [ ] Firewall
- [ ] Activity log
- [ ] SSH
- [ ] Accounts
- [ ] Settings
- [ ] General

5. Safari
- [ ] VM
- [ ] Storage
- [ ] Snapshots
- [ ] Images
- [ ] Firewall
- [ ] Activity log
- [ ] SSH
- [ ] Accounts
- [ ] Settings
- [ ] General

**Comment by rennervo** [comment]
1) Snapshot list: Action box icon isn't correct displayed if type of displaying is list
Steps:
1. Log in and go to Snapshots
2. Select date with created snapshots
3. Select displayed type is "List"

Actual result: Icons of snapshots are displayed correctly.
Expected result: "More_" instead of the action box icon

Screenshot:
![more_](https://user-images.githubusercontent.com/26665398/38917227-4b66c204-4314-11e8-93d2-6f3c8296b047.png)

2) Image list/sidebar: Delete icon there isn't  in image action box
Steps:
1. Log in and go to Images
2. Press on action box of any Template/ISO (image list or image sidebar)

Actual result: Delete icon there isn't in action box
Expected result: Delete icon there is in action box

Screenshot:
![delete icon images](https://user-images.githubusercontent.com/26665398/38917526-41114b02-4315-11e8-8615-d0c4ff5225e3.png)

3) Account list/sidebar: Delete icon there isn't in account action box
Steps:
1. Log in and go to Accounts
2. Press on action box of any Account (account list or account sidebar)

Actual result: Delete icon there isn't in action box
Expected result: Delete icon there is in action box

Screenshot:
![delete icon accounts](https://user-images.githubusercontent.com/26665398/38917778-ec26b694-4315-11e8-9329-37e910903a5a.png)

4) Small icons
These icons are less than neighboring icons:
- "Template" tab icon in Image sidebar
- "Images" tab icon in the main sidebar

Actual result: Icons are less than neighboring icons;
Expected result: All the uniformly icons have the same size.

Screenshots:
![small icons](https://user-images.githubusercontent.com/26665398/38917984-89f8f512-4316-11e8-957b-6a9e9393ce19.png)

5) Pending icon disappears when performing operations that have a pending status.
Steps:
1. Log in and go to VM
2. Press on action box of any running VM and select "Stop"
3. Confirm action in dialog

Actual result: Pending icon disappears, icon with number of notifications is displayed;
Expected result: Pending icon and icon with number of notifications are displayed.

Screenshot:
![pending icon](https://user-images.githubusercontent.com/26665398/38918130-f64923ae-4316-11e8-8b57-e53591e80ea8.png)

Additional information: 
The icon for converting a private SG into a shared SG was not checked, because this function is not present in this branch.

**Comment by ershovaelena** [comment]
@rennervo all problems will be fixed except "some  icons are less than neighboring icons". This is the actual size of this icon. It is decided to leave it this way for now (discussed with @tamazlykar and                      PO)

**Comment by tamazlykar** [comment]
@rennervo bugs fixed
Test on tamazlykar/1049-icons

**Comment by rennervo** [comment]
Image list/sidebar: Delete icon there isn't in image action box

Steps:
- Log in and go to Images
- Press on action box of any Template/ISO (image list or image sidebar)
- Press on "Delete" item

Actual result: Nothing happens
Expected result: A dialog appears to confirm deletion.

**Comment by tamazlykar** [comment]
@rennervo fixed
Test on 
tamazlykar/1049-icons

**Comment by rennervo** [comment]
Tested on tamazlykar/1049-icons
