### ISSUE TITLE
Get rid of BaseModel for VirtualMachine model

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1104]

**Comment by HeyRoach** [comment]
Test:
HeyRoach/1104-vm-base-model

Check all in:
Virtual machines: VM list, VM details sidebar, VM creation

**Comment by HeyRoach** [comment]
Bug appears(on master):
Steps:
1) Select VM
2) Select SSH key for VM on a sidebar
3) Click 'Change'

Actual result:
Error from server appears: "Resource [DataCenter:1] is unreachable: Unable to apply save SSHkey entry on router"

**Comment by tamazlykar** [comment]
@HeyRoach this is coming from the server, so this is not a bug.

**Comment by chewlite** [comment]
**(!) Testing isnt completed**

**_VM list_**
**1. No VM name in details sidebar**
Expected: there is a VM name

**2. Start VM - after completion the status "in progress" (yellow), all actions in action box are disabled**
Repeated for stop, reinstall, reboot, destroy
Status and actions are correct after the page is refreshed

**3. Reset password - following errors**
![2018-08-22 16-38-10](https://user-images.githubusercontent.com/32011943/44456093-ec1d1900-a629-11e8-9f30-fe4d880b53ef.png)
![2018-08-22 16-38-22](https://user-images.githubusercontent.com/32011943/44456122-fb03cb80-a629-11e8-8a29-448e3deb9def.png)

4. Filter by group ???


_**VM creation**_
**1. VM deploy error**
![2018-08-22 16-44-13](https://user-images.githubusercontent.com/32011943/44456421-a7de4880-a62a-11e8-8b7b-ad34ef34e24d.png)
VM appears in the list after the page is refreshed

**Comment by chewlite** [comment]
_**VM creation**_
**1. VM deploy error**
![2018-08-22 16-44-13](https://user-images.githubusercontent.com/32011943/44456421-a7de4880-a62a-11e8-8b7b-ad34ef34e24d.png)
VM appears in the list after the page is refreshed
Group doesnt add to VM

**Comment by chewlite** [comment]
VM details
1. Add a group to VM - error
![2018-08-23 09-35-11](https://user-images.githubusercontent.com/32011943/44501584-0b628780-a6b8-11e8-9d38-be1b68cca25a.png)

**Comment by rennervo** [comment]
Lack:2

**1) VM in a state "Destroyed" cannot be expunged without refresh page**
If you trigger an expunging action for a VM in the "Destroyed" state, then an error will appear and the VM will not disappear from the list. But after updating the page, the VM will not be listed.

**Steps:**
1) Create new VM
2) Open the action box and select "Destroy"
3) Not checking "Expunge" and confirm dialog
4) Open the action box and select "Expunge"

**Actual result:** Error appears, VM is not deleted from a list before page update (screenshot)
**Expected result:** Error not appears, VM disappears from a list after completion of expunge

**Feature ID:** vm_expunge

Screenshot:
![expunge error](https://user-images.githubusercontent.com/26665398/46712097-948a4980-cc79-11e8-9838-1d27f369410d.png)

**2) VM Group is not saved after page refreshing**
If VM is assigned to a group when creating or from sidebar and page is refreshed, then the group is not saved.

**Steps 1:**
1) Go to create VM
2) Select exist or create a new group
3) Fill to all required fields and create VM
4) Refresh the page and go to the sidebar of the VM

**Steps 2:**
1) Create new VM without a group
2) Go to the sidebar of the VM
3) Select exist or create a new group for VM
4) Refresh the page

**Actual result:** Group is not saved for VM, the "Group" area has a value "No group" (screenshot)
**Expected result:** Group is saved for VM, selected group is in the "Group" area

**Feature ID:** vm_group_change, vm_creation_vmgroup

**Screenshot:**
![group vm not saved](https://user-images.githubusercontent.com/26665398/46712622-2430f780-cc7c-11e8-8085-48d00637be7c.png)

**3) SSH key is not added to VM without the page refreshing (This error is from Lack 1)**
Error changing SSH key for VM and VM cannot be running when a change to SSH key in VM sidebar. Changes occur only after page refresh.

**Steps:**
1) Create new VM without SSH key
2) Go to the sidebar of the VM
3) Go to SSH key change
4) Select any SSH key and click "CHANGE"
5) Confirm dialog

**Actual result:** Error changing SSH key, SSH key is not changed, VM stay in "Starting" state (screenshot)
**Expected result:** Error disappears, SSH key is changed successful, VM in "Running" state

**Feature ID:** vm_sshkey_display, vm_sshkey_change

**Screenshot:**
![change ssh from vm sidebar](https://user-images.githubusercontent.com/26665398/46714000-8b9e7580-cc83-11e8-8733-129b3486eaaa.png)

**4) Deploy error for VM from a template with "password enabled" + with SSH keypair not auto-generated (This error is from Lack 1)**

**Steps:**
1) Go to SSH key section and Create new SSH key without auto-generation (example: in a field "Public key" input value "ssh-rsa 12345")
2) Make sure you have a password-enabled template. Otherwise, create it.
3) Go to VM section and click to "Create" button
4) Select a template with a password in the Installation source
5) Select SSH key, that created without auto-generation
6) Fill to all required fields and click to "Create"

**Actual result:** Error of deploy with a text "Error encrypting password" (screenshot)
**Expected result:** VM is created successfully

**Feature ID:** vm_creation_installsource, vm_creation_sshkeypair

**Screenshot:**
![2018-10-10 12-13-48](https://user-images.githubusercontent.com/26665398/46714449-b38ed880-cc85-11e8-92b1-a03a3a1c0250.png)

**5) Error when open sidebar for Firewall groups and templates**

**Steps 1:**
1) Go to the Firewall section
2) Go to "Firewall templates" tab
3) Click to any Template

**Actual result:** Sidebar of template opens, but console error with a text "Cannot read property 'find' of undefined" appears (screenshot 1)
**Expected result:** Sidebar of template opens, console error disappears

**Steps 2:**
1) Go to the Firewall section
2) Go to "Shared" or "Private" security group tab
3) Click to any firewall group

**Actual result:** Sidebar of the template not opens, many console errors appear (screenshot 2)
**Expected result:** Sidebar of template opens, console error disappears

**Feature ID:** Firewall sidebar

**Screenshot 1:**
![sidebar fw template](https://user-images.githubusercontent.com/26665398/46715060-927bb700-cc88-11e8-900a-6e40d905d60d.png)

**Screenshot 2:**
![fw groups sidebar error](https://user-images.githubusercontent.com/26665398/46715066-99a2c500-cc88-11e8-85a0-c6d0e9a2a187.png)

**Comment by HeyRoach** [comment]
@rennervo 
To test only logic (that is you can test in only one browser)

Also to test:
image_template_create
volume_create, resize and remove
snapshot_create

**Comment by rennervo** [comment]
Lack:3

**1) Error №4 from "Lack:2" is repeated**

**2) VM group is not removed from VM sidebar**

**Steps 1:**
1. Create new VM with group
2. Refresh the page
3. Go to the sidebar of created VM
4. Click to "change group" icon
5. Select "Remove from the group <group_name>"
6. Click to "REMOVE" button

**Steps 2:**
1. Create new VM without a group
2. Go to the sidebar of created VM
3. Click to "change group" icon
4. Select exist or create new VM group
5. Click to "ASSIGN" button
6. Refresh the page
7. Click to "change group" icon
8. Select "Remove from the group <group_name>"
9. Click to "REMOVE" button

**Actual result:** Group is not deleted, in the console, an error appears with the text "Cannot read property 'name' of undefined",  "Removing an instance group” operation is performed indefinitely in pending dialog. (screenshot)
**Expected result:** Group is deleted, no console error.

**Screenshot:**
![vm group is not deleted](https://user-images.githubusercontent.com/26665398/46940492-09eb8500-d093-11e8-8962-8af3ec5e19f9.png)

**Comment by HeyRoach** [comment]
@rennervo 
1 - is not our bug (reproduce on master also) it is cloudstack api bug

**Comment by Nadya913** [comment]
Tested on branch
