### ISSUE TITLE
Error appers when changing limits of Account with project limit "infinity"

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1114]
### Steps to reproduce
1. Go to Accounts and open a sidebar of any account that has "infinity" value for "project limit"
2. Change one of the limits and save changes

### Actual result

Error "Unable to execute API command updateresourcelimit due to invalid value Infinity for parameter max" appears

### Expected result

The limit is changed, the error does not appear

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

- account_limits_display
- account_limits_change

**Comment by tamazlykar** [comment]
**Test on:**
tamazlykar/1114-account-limits

**Regression:**
account_limits_display
account_limits_change

**Comment by rennervo** [comment]
**Value "Infinity" cannot be saved when it enters instead of numeric values**
The value "Infinity" replaces the value "-1", but the user does not know it. And if the user wants to change the integer value of the limit to "Infinity", then a value error will be received.

Steps:
1. Log in and go to Accounts
2. Go to sidebar any not disabled account
3. Press icon of edit account limit
4. Change any numeric values to value "Infinity"
5. Press "Save"

Actual result: Error of invalid value "Infinity" it appears, changed values aren't saved
Expected result: **A discussion with the PO or PM is required**:
- An invalid value error appears with a prompt that you can enter "-1" for an infinite limit or a value from 0 or more.
OR
- Value "Infinity" is true, the value is changed to "-1" in a request body
OR
- Any other way
![save value infinity](https://user-images.githubusercontent.com/26665398/41835532-28c6b7c4-7882-11e8-9dd8-ab1859873301.png)

**Comment by tamazlykar** [comment]
@rennervo test again, please

**Comment by rennervo** [comment]
**An error occurs and limit changes are not saved when entering the value "Infinity" from a small letter - "infinity"**

Steps:

1. Log in and go to Accounts
2. Go to sidebar any not disabled account
3. Press icon of edit account limit
4. Change any values to value "**infinity**"
5. Press "Save"

Actual result: Changes aren't saved, an error occurs
Expected result: Changes are saved, a value saves as -1 and displays as "Infinity"
![small letter infinity](https://user-images.githubusercontent.com/26665398/42436648-dcae61f8-8384-11e8-87af-7bdc5548fefe.png)

**Comment by tamazlykar** [comment]
Made value independent of the register

**Comment by rennervo** [comment]
Tested on /tamazlykar/1114-account-limits/
