### ISSUE TITLE
Add validators for config parameters

### ISSUE THREAD

**Issue by tamazlykar** [bwsw/cloudstack-ui#1200]
1. Need to add non-existing validators for config parameters that user can change
2. Describe property interface in Config interface for parameters you have been validated. 

Parameters:

- [x] API Doc Link
- [x] VM colors
- [x] Security Group Templates
- [x] Offering Compatibility Policy
- [x] Allow Reordering Sidenav

See [Config Guide](https://github.com/bwsw/cloudstack-ui/blob/master/config-guide.md) for more information

**Comment by wowshakhov** [comment]
To test:
config_api_doc_link
config_vm_color
config_firewall_template_system
config_so_compatibility
config_sidebar_reorder

Test that when these config params are specified incorrectly in config.json, an approprate warning is given in the console. For example, if required fields are missing, if params are misshapen (extra fields, incorrect types), if there are several entries with same ids.

**Comment by tamazlykar** [comment]
Please also test that config-example is valid.

**Comment by rennervo** [comment]
Lack:1

**1) Configuration "apiDocLink" cannot be an empty string**

**Steps:**
1. Set empty string ( "" ) to "apiDocLink" in config.sjon
2. Go to the system in the Settings section

**Actual result:** The empty string is not checked, the "Documentation" parameter is empty in the settings (screenshot)
**Expected result:** Checking the empty string is carried out, a message is displayed in the console that the string cannot be empty, in the settings the "Documentation" parameter has a default value. 

**Screenshot:**
![apidoclink is empty](https://user-images.githubusercontent.com/26665398/46927534-1efaf080-d060-11e8-9ff2-773244263d70.png)

**2) Configuration "apiDocLink" must be in link format**

**Steps:**
1. Set not link ( "asd123" ) to "apiDocLink" in config.sjon
2. Go to the system in the Settings section

**Actual result:** The string is not checked for the format of the link, the entered value is displayed in the settings (screenshot)
**Expected result:** The string is checked for the format of the link. If the string is not a link, then an error message is displayed in the console, the default value is displayed in the settings.

**Screenshot:**
![apidoclink is not link](https://user-images.githubusercontent.com/26665398/46927650-b4968000-d060-11e8-9a92-0b49e78c2cb0.png)

**3) One color can be added several times in the "vmColors"**

**Steps:**
1. Set following value for "vmColors" in config.json:
"vmColors": [
  { "value": "#F44336" },
  { "value": "#F44336" },
  { "value": "#F44336" }
]
2. Go to the system in the VM section
3. Go to sidebar of any VM
4. Click on the button to change the color of the VM

**Actual result:** Section for change the color of the VM is opened, one color is displayed several times (screenshot)
**Expected result:** The console displays an error of having several identical colors, in the color picker for the VM the default palette is displayed.

**Screenshot:**
![one color for vm](https://user-images.githubusercontent.com/26665398/46928327-3d62eb00-d064-11e8-824f-f0b3b3ad3f46.png)

**4) Ignored tags must be unique to the configuration "offeringCompatibilityPolicy"**
The tag name is a unique parameter, so it cannot be repeated.

**Steps:**
1. Set following value for "offeringCompatibilityPolicy" in config.json:
"offeringCompatibilityPolicy":{
"offeringChangePolicyIgnoreTags": ["t1", "t1"]
}
2. Go to the system

**Actual result:** The console does not contain an error about duplicate tags.
**Expected result:** The console contains an error about duplicate tags, the default parameter is used.

**5) The "config-example" contains the id of the entities that may not exist for the user.**
For example, IDs of entities are present in the parameters "customComputeOfferingParameters", "defaultComputeOffering", "computeOfferingClasses". If you simply copy the data from the config-example.json file to the config.json file, then errors will occur in the system, because these entities do not exist.

**Actual result:** File "config-example.json" contains the id of specific entities.
**Expected result:** In those places where the ID should be indicated is the inscription "enter the entity ID"

**6) Parameter "ruleid" cannot be an empty string**
This parameter is required. If it is empty, then the system does not display all groups and templates for SG.

**Steps:**
1. Set empty string ( "" ) in "ruleid" for "securityGroupTemplates" in config.sjon
2. Go to the system in the Firewall section 

**Actual result:** There is no error in the console, all security groups and security templates are not displayed.
**Expected result:** In the console there is an empty error for the "ruleid", all groups and security templates are displayed, the default settings for the "securityGroupTemplates" are used

**7) Parameter "name" cannot be an empty string**
This parameter is required and it cannot be an empty string

**Steps:**
1. Set empty string ( "" ) in "name" for "securityGroupTemplates" in config.sjon
2. Go to the system in the Firewall section 

**Actual result:** There is no error in the console, the template has no name (screenshot)
**Expected result:** In the console there is an empty error for the "name", the default settings for the "securityGroupTemplates" are used

**Screenshot:**
![templates has no name](https://user-images.githubusercontent.com/26665398/46929989-25dc3000-d06d-11e8-980a-5e00162f2714.png)

**8) You can create rules with the same parameters**
According to the system requirements, you cannot create rules with identical settings inside the "ingressrule" / "egressrule" . This is so necessary to validate. The parameter "ruled" is not included in this test.

**Steps:**
1. Set following value for "securityGroupTemplates" in config.json:
"securityGroupTemplates": [
 {
      "id": "templateTCP",
      "name": "TCP Permit All",
      "description": "Permits all TPC traffic",
      "preselected": false,
      "ingressrule": [
        {
          "ruleid": "id-1",
          "protocol": "tcp",
          "startport": 1,
          "endport": 65535,
          "cidr": "0.0.0.0/0"
        },
        {
          "ruleid": "id-2",
          "protocol": "tcp",
          "startport": 1,
          "endport": 65535,
          "cidr": "0.0.0.0/0"
        }
      ],
      "egressrule": [ ]
 }
]
2. Go to the system in Firewall section

**Actual result:** There are no errors about the same rules in the console, the same rules are displayed in the system template rules viewing window.
**Expected result:** An error about identical rules appears in the configuration "securityGroupTemplates" in the console, the default settings are used

**9) The "cidr" parameter cannot be empty and should check the value for compliance with the IPv4 or IPv6 standard**
The "cidr" parameter is required, so it cannot be an empty string.
Also, the parameter should be checked for compliance with the IPv4 or IPv6 standard, depending on the entered value.
IPv4 standard - https://ru.wikipedia.org/wiki/IPv4
Format: 0-255.0-255.0-255.0-255/0-32
IPv6 standard - https://ru.wikipedia.org/wiki/IPv6
Format: 0000-FFFF:0000-FFFF:0000-FFFF:0000-FFFF:0000-FFFF:0000-FFFF:0000-FFFF:0000-FFFF/0-128

Patterns to verify compliance with the standards is already present in the CSUI, in the SG creation/modification block.

**Actual result:** For the "cidr" field there is no check for an empty line, and checking for compliance with standards. Any line entered will be displayed in the rules view window.
**Expected result:** The "cidr" parameter is checked for an empty string and for compliance with standards. If an invalid value occurs in the console, an error occurs and the default value is used for the "securityGroupTemplates" configuration.

**Screenshot (invalid cidr):**
![invalid sidr](https://user-images.githubusercontent.com/26665398/46930852-6f7b4980-d072-11e8-9598-53ede2ed972a.png)

**Comment by wowshakhov** [comment]
8) You can create rules with the same parameters
Can't be done with ajv, which is used for config validation

**Comment by tamazlykar** [comment]
@wowshakhov use [uniqueitems](https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md#uniqueitems)

**Comment by tamazlykar** [comment]
9. cidr is too long to fit into json validation

**Comment by rennervo** [comment]
10 error will be fixed in task [1336](https://github.com/bwsw/cloudstack-ui/issues/1336)

**Comment by Nadya913** [comment]
Testing stopped on 5
