### ISSUE TITLE
Can not copy information from VM tab

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#1223]
When I have created a VM, usually I would like to copy IP4, IP6 and other stuff to the clipboard. Now sidebar prevents from copying the texts. Users will not like that behavior. Maybe I don't see the whole IPv6 address and other stuff, but I wish to copy the information, at least. 

**Connected feature ID:** vm_NIC_display

**Comment by ershovaelena** [comment]
@bwsw 2 possible ways:
1. a possibility to copy all elements in "NIC configuration" section by selecting the text (as in other tabs of the sidebar)
2. a possibility to copy by clicking on value (like we have for tag values). If this implementation is needed, please specify for which elements it should be applied: 
- IPv4
- MAC address
- Gateway v4
- IPv6 address
- IPv6 CIDR
- IPv6 gateway
- Secondary IP

Which variant is preferable?

**Comment by bwsw** [comment]
@ershovaelena 1st

**Comment by HeyRoach** [comment]
Test:
vm_NIC_display

**Comment by chewlite** [comment]
@HeyRoach 

lack:1

**1. There is no capability to copy labels** 

Expected result: 
We can copy labels and values in NIC configuration because in the other tabs there is this capability. 
From @ershovaelena comment: "a capability to copy **all elements** in "NIC configuration" section by selecting the text **(as in other tabs of the sidebar)**"

**2. There is no capability to copy values in IE and Edge**
@ershovaelena should we fix this? IE and Edge aren't the main browsers for support

**Comment by ershovaelena** [comment]
@HeyRoach @chewlite 
1. Yes, a user should be able to copy both labels and values 
2. @HeyRoach fix Edge and IE if it's fast. If it's a problem, let me know.

**Comment by rennervo** [comment]
Tested on 1249
