### ISSUE TITLE
New VM create dialog hangs very often not showing actual dialog

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#1228]
It hangs before showing actual parameters which can be configured for a new vm.

**Connected feature ID:** no special ID. Opening a VM creation dialog.

**Comment by rennervo** [comment]
I could not track the cause of the error, because errors in the console are not present and in the network tab for all requests code 200.
However, I managed to reproduce the error. An error may occur for a user with the "User" role in the following cases:
1) Switch between the main sections and click on the VM create button
2) Click on the switcher of used resources "Used / Free" and click on the VM create button
3) Multiple button pressing for VM create

**Comment by tamazlykar** [comment]
The bug is played when some requests come later than should and the system does not react to them.
Regression: vm_creation

**Comment by Nadya913** [comment]
Tested on 1270
