### ISSUE TITLE
Distinguish between "VM display name" and "VM host name"

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#1269]
This issue covers the following requirements:
1. [REQ_VM_CREATE_001] A user should be able to define a display name of the VM (VM creation)
2. [REQ_VM_CREATE_023] The System should automatically generate VM host name (VM creation)
3. [REQ_VM_DTLS_003] A user should be able to view general information about VM (hostname, zone)

**Comment by chewlite** [comment]
lack:1

@HeyRoach 

**1. The host name doesn't generate automatically**

Steps:
1. Open the VM creation
2. Fill all fields by valid values
3. “VM host name” field remains empty
4. Click Create

**Actual result:** ![2018-10-30 15-24-18](https://user-images.githubusercontent.com/32011943/47708804-794fa000-dc61-11e8-98d0-02ff168fbfaa.png)
**Expected result:** 
autogenerated VM host name value in the query parameter "name", VM created successfully

**2. VM host name appears instead of VM display name in _shared SG sidebar_ and _private SG card_**
![2018-10-30 16-24-37](https://user-images.githubusercontent.com/32011943/47709266-7608e400-dc62-11e8-8370-0900004afb75.png) ![2018-10-30 16-25-00](https://user-images.githubusercontent.com/32011943/47709275-799c6b00-dc62-11e8-993b-ff0983b72b6e.png)

**3. In “VM display name” and “VM host name” fields the value by one symbol is invalid**
![2018-10-30 16-26-15](https://user-images.githubusercontent.com/32011943/47708446-acddfa80-dc60-11e8-96fd-763157a27dd1.png) ![2018-10-30 16-26-05](https://user-images.githubusercontent.com/32011943/47708448-acddfa80-dc60-11e8-837e-0163f5b55040.png)

**4. Space after Details block is bigger than other spaces in the VM sidebar**
![2018-10-30 14-26-14](https://user-images.githubusercontent.com/32011943/47709490-eb74b480-dc62-11e8-8bed-28ea40cb36e2.png)
