### ISSUE TITLE
[Log View] Load logs when many files

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1376]
This issue covers the following requirements:
1. [REQ_LOGS_013] A load should be implemented in case of a large number of records

**Comment by wowshakhov** [comment]
1) Currently page size is 100 entries. If there are more than 100 entries and user scrolls to the end of the screen, additional 100 entries are shown.
2) If autoupdate is enabled and new entries are shown at the bottom, on each update screen scrolls to the top of the last entry.
3) If new entries are shown at the top, auto scroll should not happen.
4) Scroll loading also works in auto update mode, but it is impossible to test at the moment, because the current frequency of updates is insufficient to generate 100+ entries per minute in the autoupdate mode.
