### ISSUE TITLE
Manage maximum VM snapshots amount in config.json

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#1415]
A part of an epic #412

This issue covers the following requirements:
[REQ_VM_DTLS_050] A user should be able to configure the maximum number of VM snapshots in the configuration file.

**Comment by HeyRoach** [comment]
Test:
REQ_VM_DTLS_050

**Comment by rennervo** [comment]
Lack: 1
Tested on 1523 in the simulator

**1) Parameter "vmSnapLimit" is unknown**

The feature does not work, because The system cannot determine the parameter entered.

![2019-01-25 10-40-55](https://user-images.githubusercontent.com/26665398/51724499-35b5d800-2090-11e9-800c-2743d9bb03ea.png)

**2) Make sure that there is validation for the "vmSnapLimit" parameter.**

- Integer values only
- Only positive values or zero

**3) The documentation does not specify the object to which the restriction applies.**

Specify in the user-guide more explicitly an object that is subject to a limit on the number of snapshots created. (Domain, account, user or VM)

**Comment by rennervo** [comment]
Tested on 1523 in the simulator
