### ISSUE TITLE
Distinguish IPv4/IPv6 in Security Group rules view mode

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#671]
**Acceptance criteria:**

1. Ingress SG rules are displayed incorrectly. Semantics should be like:

- Protocol (correct)
- ICMP or Ports (correct)
- **FROM** CIDR (incorrect - now is **TO**)

2. Distinguish IPv4 and IPv6. Correct:

Incoming TCP traffic **from** **IPv4** X.X.X.X/Y to **VM** (add the word) port range M-N
Incoming TCP traffic **from** **IPv6** X:Y::C/D to **VM** (add the word) port range M-N

Outgoing TCP traffic to **IPv4** X.X.X.X/Y to port range M-N	
Outgoing TCP traffic to **IPv6** X:Y::C/D to port range M-N	

IPv4 and V6 addresses can be easily distinguished with Regexp.

3. IPv4/IPv6 rules filtering: 
Filtering when view - add new **2 checkboxes ipv4, ipv6** on the right side of 2 existing filterings

**Connected feature ID:** 
- _firewall_rules_view_
-  _firewall_rules_view_filter_
- _vm_firewall_rules_view_

**Comment by bwsw** [comment]
To move enchancements to ipv6 impl ticket

**Comment by bwsw** [comment]
Might be it's better to implement new rule creation as modal dialog? It help define the context like, if i chosen incoming then show From if outgoing then To, like single screen master when context of the first field dwfines the next. Just to think about it...

**Comment by ershovaelena** [comment]
A comment of 18.11.17 is moved to a separate issue #903

**Comment by qqcky** [comment]
**To test:** 
- firewall_rules_view_filter
- firewall_rules_view
- firewall_rules_edit

Test on `qqcky/671-ipv6-support`.

**Comment by rennervo** [comment]
Errors:
1. The system incorrectly determines the type of CIDR. All the rules that are created are defined as IPv6, even if it's IPv4. Because of this, the following errors occur:
 - Data is false in a row with a new rule. CIDR type is IPv6 instead of IPv4.
![ipv4 vs ipv6](https://user-images.githubusercontent.com/26665398/35897553-51865d22-0bf4-11e8-80eb-c5576a856790.png)
 - Items in fields "ICMP type" and "ICMP code" not matching with ICMPv4 protocol when an ICMPv4 rule is creating. In this case in these fields are items from the ICMPv6 protocol.

2. When displaying rules between words "TCP/UDP" and "traffic" there is no space when incoming rule is creating with protocol type is TCP or UDP and same start and end port (Only for English version)
![tcp and udp space](https://user-images.githubusercontent.com/26665398/35897885-0d859276-0bf6-11e8-8d33-ac9c69091fb9.png)

3. In egress rule doesn't specify the type of CIDR (Only for Russian version) when displaying rules.
![cidr type russian](https://user-images.githubusercontent.com/26665398/35898121-321d8098-0bf7-11e8-9f21-93ce37eac1c1.png)

**Comment by rennervo** [comment]
Invalid items in a drop-down list of "ICMP type" field when creating a new rule with IPv4 protocol.

![security](https://user-images.githubusercontent.com/26665398/35954618-3e0df98e-0cbd-11e8-9514-381d4a639b85.png)

**Comment by rennervo** [comment]
@qqcky 
Tested on qqcky/671-ipv6-support

**Comment by chewlite** [comment]
for @qqcky 

Tested on master

_**firewall_rules_view, vm_firewall_rules_view**_
v4/v6 filter isn't on the right side of two other filters
![filters](https://user-images.githubusercontent.com/32011943/36362703-ac13b676-1569-11e8-969b-b34e8c2ddd1d.png)

**_firewall_rules_edit, vm_firewall_rules_edit_**
1) IP without subnet mask is valid and add-button is enable.
Rule isn't added, "errortext":"Invalid cidr *value*" in http response
![ip without subnet mask](https://user-images.githubusercontent.com/32011943/36362715-c959a9c0-1569-11e8-8021-b9cc816b14f2.png)

2) The rule is added when ipv6 and ICMP type/code (-1,-1) 
![v6-1-1](https://user-images.githubusercontent.com/32011943/36362725-ecf28190-1569-11e8-9321-76a659de5404.png)

3) IP is invalid, but add-button is enable. 
Rule isn't added, "errortext":"Invalid cidr *value*" in http response
![invalid cidr but add is enable](https://user-images.githubusercontent.com/32011943/36362892-15bd0c52-156b-11e8-909d-dda9b83b4c1d.png)

**Comment by chewlite** [comment]
Tested on master

Detected issues:
[#997](https://github.com/bwsw/cloudstack-ui/issues/997)
[#998](https://github.com/bwsw/cloudstack-ui/issues/998)
