### ISSUE TITLE
Get rid of BaseModel for Snapshot model 

### ISSUE THREAD

**Issue by HeyRoach** [bwsw/cloudstack-ui#788]

**Comment by qqcky** [comment]
*To test*: 
- _vm_disk_snap_create_
- _vm_disk_snap_schedule_
- _vm_disk_snap_display_
- _vm_disk_snap_delete_
- _vm_disk_snap_template_create_
- _storage_actionbox_
- _storage_snap_create_
- _storage_snap_schedule_
- _storage_snap_display_
- _storage_snap_delete_
- _storage_snap_template_create_

Test on `qqcky/788-snapshot-model`

**Comment by Nadya913** [comment]
**storage_snap_display**
http://cs-ui-ci.z1.netpoint-dc.com:8080/qqcky/788-snapshot-model/storage/1a906e5a-b3e5-4a8e-98a1-6446d95d190b/snapshots
Double "No results" text appears instead of snapshot.

Steps:
1. Login and press on running vm
2. Go to Disks and create any snapshot for disk
3. Go to Storage and see the snapshots in sidebar

Expected: Snapshot is shown
Actual: No results appears twice
![788-snapsdisplay](https://user-images.githubusercontent.com/33111683/34709475-ff0758d2-f549-11e7-844c-6c413f7981ed.png)

**Comment by Nadya913** [comment]
Tested on http://cs-ui-ci.z1.netpoint-dc.com:8080/qqcky/788-snapshot-model
