### ISSUE TITLE
"Convert to shared" feature for Private security groups 

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#821]
Connected to #816 

**Acceptance criteria:**
1. "Convert to shared" ("Сделать общей") button in action box of security group
2. A warning dialog appears. If YES is clicked, then SG is moved to "Shared SG" tab (tag "is private" is removed). If NO is clicked, then SG stays private.
3. Custom feature - to describe in "Custom features" local doc

**Connected feature ID:** _firewall_list_private_convert_, _firewall_actionbox_

Mockup 
![816](https://user-images.githubusercontent.com/26703076/34239223-753894b0-e638-11e7-8198-b29742660e89.jpg)

**Comment by HeyRoach** [comment]
Will be a part of #816

**Comment by HeyRoach** [comment]
It is solved in #816 and commented now

**Comment by HeyRoach** [comment]
HeyRoach/821-private-to-shared

Test to:
firewall_list_private_convert, 
firewall_actionbox

**Comment by HeyRoach** [comment]
Try to do: (fir fixing problem with cache)
1) get rid of cache data
2) update cache - it is a better way

**Comment by rennervo** [comment]
1. **Private SG tags are deleted after convert in Shared SG and refresh of the page.**
Actual result: All tags of Private SG are deleted;
Expected result: Only "csui.security-group.type" tag is deleted, and other tags are saved;
![convertation tags](https://user-images.githubusercontent.com/26665398/36405610-2584ce04-1624-11e8-973c-14918b49eb39.png)

2. **Errors caused by a problem with updating the cache (occur if page isn't refreshed)**

**2.1 Deleting Converted Shared SG after deleting parent VM**

Steps:
1) Log in and go to VM;
2) Create VM without selecting Shared SG;
3) Go to Private SG and convert Private SG of created VM to Shared;
4) Go to VM and delete this VM;

Actual result: Converted Shared SG is deleted after deleting parent VM;
Expected result: Converted Shared SG isn't deleted after deleting parent VM;

**2.2 Deleted "type" tag of converted Shared SG appears again if you switch between main tabs**

Steps:
1) Log in and go to Private SG;
2) Convert any Private SG to Shared;
3) Go to any other tab in left-side menu and return to Firewall tab; 

Actual result: Converted SG is Private and "type" tag appears again;
Expected result: Converted SG is Shared and "type" tag absents;

**Comment by rennervo** [comment]
After fixed (for QA):
Check the ability to delete SSG after the VMs associated with it have been deleted.

**Comment by chewlite** [comment]
Test on 972

**Comment by chewlite** [comment]
@HeyRoach 

**SG tags are deleted after converting**

Steps:
1. Add a few tags for Private SG
2. Convert this Private SG to Shared
3. Open SSG tab
4. Refresh the page
5. Open details sidebar of just converted SG

Actual: no tags
Expected: there are all tags besides "csui.security-group.type - private"

**Comment by chewlite** [comment]
@HeyRoach 

Tested on 972
