### ISSUE TITLE
Remove "lock/enable account" feature from Accounts

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#887]
Please remove "lock/enable account", there should be only "disable/enable" in action box for accounts.

**Connected feature ID:** _account_lock, account_enable_

**Comment by HeyRoach** [comment]
HeyRoach/887-account-actions
To test:
account_lock,
account_enabled

**Comment by rennervo** [comment]
You need to correct the text about the error when trying to log into the system of the disabled account.
Instead of "disabled/locked", you just need to write "disabled".
Branch: HeyRoach/887-account-actions
![failed text about error](https://user-images.githubusercontent.com/26665398/35144935-9eb32b5e-fd38-11e7-9654-bb892da32b1a.png)

**Comment by rennervo** [comment]
Tested on HeyRoach/887-account-actions
