### ISSUE TITLE
IPv6 support in Security Group rules edit mode

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#920]
**Acceptance criteria:**

1. Support entering IP addresses in both IPv4 and IPv6 formats (the 3d field). There should be a text `CIDR v4/v6` pre-entered in this field.

2. Support _ICMPv6_ correctly. Allow valid ICMPv6 types and codes.
(-1, -1) is incorrect for ICMPv6. Basically a user can specify -1,-1 for ICMP but lately, ACS firewall code raises errors and rules are skipped, so we have to filter it on client side allowing (right now) only valid ICMPv6 types and codes.

Consult this page: https://www.iana.org/assignments/icmpv6-parameters/icmpv6-parameters.xhtml

**Connected feature ID:** _firewall_rules_edit_, _vm_firewall_rules_edit_

**Comment by qqcky** [comment]
**To test:**
firewall_rules_edit

Test on `qqcky/920-ipv6-support`

**Comment by rennervo** [comment]
Failed.
1. Log in page doesn't load in IE Browser (ver. 11.192.16299.0). 
An error appears "SCRIPT1014: Invalid character
main.8bb7c1a3fdd949e2b758.bundle.js (1,3265123)" in Console. (qqcky/920-ipv6-support)
2. "Start port" and "End port" fields of TCP/UDP protocols allow to enter 65536. It's error, because max port is 65535.
3. "ICMP type" and "ICMP code" fields of ICMPv6 protocol allow to enter (-1, -1). It's error, because these values supports only ICMPv4, but for ICMPv6 these values are incorrect.

**Comment by qqcky** [comment]
Will be closed by #671 (PR #957)

**Comment by rennervo** [comment]
Invalid items in a drop-down list of "ICMP type" field when creating a new rule with IPv4 protocol.
![security](https://user-images.githubusercontent.com/26665398/35954539-dfd35f08-0cbc-11e8-8a57-a2743fa129db.png)
